const SCENARIOS = [
  "Klassen har fået det dårligt efter at have spist i kantinen.",
  "En kæmpe drage lander i skolegården.",
  "Julemanden står pludselig i klasselokalet.",
  "Den sure lærer opdager, at hans kaffe er spildt.",
  "En nervøs vikar starter sin allerførste time.",
  "Brandalarmen går midt i en vigtig prøve.",
  "En elev råber, at der er en edderkop i klassen.",
  "Skolelederen kommer uanmeldt ind i timen.",
  "Klassen opdager, at de skal have idræt udenfor i regnvejr.",
  "En bold smadrer en rude i skolegården.",
  "Klassen finder en mystisk kasse foran døren.",
  "En elev påstår, at tasken bevæger sig.",
  "En kendt fodboldspiller besøger skolen.",
  "En klassekammerat har glemt alt sit tøj til idræt.",
  "Klassen opdager, at de har fået en ny superstreng lærer.",
  "Der lugter virkelig mærkeligt i klasselokalet.",
  "En elev har taget sin lillebror med i skole.",
  "Klassen vinder en kæmpe pokal.",
  "En lærer begynder pludselig at danse.",
  "Klassen opdager, at de er kommet i den forkerte bus.",
  "Hele skolen mister strømmen.",
  "En elev taber hele sin madpakke på gulvet.",
  "Klassen møder en meget streng skoleinspektør.",
  "Der ligger sne i hele klasselokalet.",
  "En hund løber ind i skolegården.",
  "Klassen opdager, at de har glemt deres lærer på turen.",
  "En elev siger, at der er en slange i busken.",
  "Klassen skal pludselig optræde foran hele skolen.",
  "En lærer kan ikke finde sine briller.",
  "Der er kun én stol tilbage i klassen.",
  "Klassen opdager, at de har fået dobbeltlektier.",
  "En ballon springer midt i timen.",
  "Skolekøkkenet står fuld af røg.",
  "Klassen finder en skattekiste på legepladsen.",
  "En elev har farvet sit hår helt grønt.",
  "Der står en meget vred forælder i døren.",
  "Klassen ser en meteor på himlen.",
  "En lærer græder over en ødelagt kop.",
  "Klassen opdager, at de skal have prøve hele ugen.",
  "En elev har taget en kæmpe is med i skole.",
  "Der står en tryllekunstner i klassen.",
  "Klassen opdager, at gulvet er helt vådt.",
  "En elev falder dramatisk af stolen.",
  "Klassen finder en hemmelig dør bag reolen.",
  "En lærer mister tålmodigheden.",
  "Klassen opdager, at de er låst ude.",
  "En elev påstår, at de har set en alien.",
  "Hele klassen får besked om at rydde op nu.",
  "En robot kommer ind i klasselokalet.",
  "Klassen opdager, at de har vundet en konkurrence.",
  "En lærer snubler over en taske.",
  "Klassen opdager, at det er deres fødselsdag alle sammen.",
  "Der sidder en kat på lærerens stol.",
  "En elev har glemt sit navn på prøven.",
  "Klassen opdager, at de skal på lejrskole i morgen.",
  "En meget træt lærer forsøger at undervise.",
  "Klassen opdager, at de er de eneste på skolen.",
  "En elev kommer for sent med en vild forklaring.",
  "Der ligger konfetti over hele gulvet.",
  "Klassen opdager, at nogen har spist lærerens kage.",
  "En elev har bygget et tårn, der er ved at vælte.",
  "Klassen opdager, at de skal synge solo.",
  "En meget streng dommer står i døren.",
  "Der lander en drone i skolegården.",
  "Klassen opdager, at de har glemt deres idrætsdag.",
  "En elev har malet på tavlen.",
  "Klassen opdager, at de har fået en klassemaskot.",
  "En lærer taber alle sine papirer.",
  "Klassen opdager, at de skal have vikar resten af året.",
  "En elev har taget en kæmpe kage med.",
  "Hele klassen får hikke på samme tid.",
  "En meget sur pedel opdager rod i gangen.",
  "Klassen opdager, at de skal rydde hele skolegården.",
  "En elev gemmer sig under bordet.",
  "Der hænger en seddel med “Rektor vil tale med jer”.",
  "Klassen opdager, at de skal i fjernsynet.",
  "En lærer prøver at være cool.",
  "Klassen opdager, at der er byttet om på klasselokalerne.",
  "En elev har taget sin hamster med.",
  "Klassen opdager, at de har glemt madpakken derhjemme.",
  "En kæmpe regnskyl starter midt i frikvarteret.",
  "Klassen opdager, at de har fået en ny klassekammerat.",
  "En elev vælter et glas vand ud over computeren.",
  "Klassen opdager, at de skal løbe 5 km i idræt.",
  "En meget glad lærer deler karakterer ud.",
  "Klassen opdager, at de har matematik i fire timer.",
  "En elev har taget en højttaler med og spiller musik.",
  "Klassen opdager, at der er en hemmelig besked på tavlen.",
  "En lærer hvisker noget meget alvorligt.",
  "Klassen opdager, at det er sidste skoledag før ferie.",
  "En elev påstår, at skolen er hjemsøgt.",
  "Klassen opdager, at deres klasseværelse er malet i en vild farve.",
  "En lærer bliver forskrækket af en høj lyd.",
  "Klassen opdager, at de har glemt deres projekt derhjemme.",
  "En elev har lavet en kæmpe tegning på tavlen.",
  "Klassen opdager, at de skal have gæster i timen.",
  "En meget dramatisk undskyldning gives midt i klassen.",
  "Klassen opdager, at de skal lave gruppearbejde med deres “modsætning”.",
  "En elev jubler, mens resten ser chokerede ud.",
  "Klassen opdager, at klokken faktisk allerede har ringet ud.",
  "Lillebror nægter at børste tænder.",
"Familien opdager, at nogen har taget det sidste stykke pizza.",
"En mobil falder i toilettet.",
"En is ryger direkte ned på asfalten.",
"Far opdager i lufthavnen, at kufferten er glemt derhjemme.",
"To søskende vil sidde på den samme plads i bilen.",
"En ven afslører en hemmelighed foran de andre.",
"Familien opdager, at bilen ikke vil starte.",
"Der går hul på en pose mel i køkkenet.",
"En hund løber væk fra snoren i parken.",
"En vennegruppe opdager, at én har snydt i et spil.",
"Strømmen går midt i den mest spændende del af filmen.",
"En ballon slipper fri og flyver op i himlen.",
"Familien opdager, at fryseren har stået åben hele natten.",
"En bold ryger ind i naboens have.",
"En gave tabes på gulvet lige før den skal gives.",
"To søskende opdager, at der kun er én dessert tilbage.",
"En ven møder op i helt forkert tøj til festen.",
"En sodavand eksploderer, da den åbnes.",
"Familien farer vild på vej til en fødselsdag.",
"En lillebror har tegnet på væggen.",
"En ven glemmer billetterne til biografen.",
"En cykel punkterer på vej til træning.",
"En hund stjæler mad fra bordet.",
"En ven kommer for sent med en dramatisk forklaring.",
"En kage vælter, lige før den skal serveres.",
"To venner vil have den samme plads i sofaen.",
"En mobil forsvinder midt i en overnatning.",
"Familien opdager, at nogen har brændt maden på.",
"En ven trykker på alle knapper i elevatoren.",
"En ballon springer med et kæmpe brag.",
"En lillebror gemmer slikposen.",
"Familien opdager, at de har glemt tandbørster på ferien.",
"En ven falder dramatisk på rulleskøjter.",
"En kat vælter et glas ned fra bordet.",
"En forælder siger 'vi skal tale sammen' med alvorlig stemme.",
"En bold rammer en vase i stuen.",
"To søskende skyder skylden på hinanden.",
"En ven sender en besked til den forkerte person.",
"Familien opdager, at toget kører om ét minut.",
"En lillebror nægter at tage flyverdragt på.",
"En ven afslører en overraskelse for tidligt.",
"Familien opdager, at der er vand over hele badeværelset.",
"En gave kan ikke åbnes, fordi tapen sidder fast overalt.",
"En ven har taget den sidste ispind.",
"En mobil tabes ned i en vandpyt.",
"Familien står klar til at tage et fælles billede, men ingen står stille.",
"En hund ryster sig midt i stuen efter regnvejr.",
"To venner bliver uvenner midt i et spil.",
"En lillebror gemmer sig for at undgå at gå i seng.",
"En familie opdager, at bilen har fået en parkeringsbøde.",
"En ven har glemt at slukke mikrofonen på et opkald.",
"En bold lander midt i en grillfest.",
"En ven mister noget vigtigt på stranden.",
"En forælder opdager, at nogen har brugt hele det varme vand.",
"En søskende har taget den andens tøj uden at spørge.",
"En familie opdager, at de har glemt fødselsdagen.",
"En ven jubler, mens de andre ser chokerede ud.",
"En lillebror skyder skylden på storesøster.",
"En mobil glider ned mellem sofaens puder.",
"En ven dukker op uanmeldt sent om aftenen.",
"En familie opdager, at nogen har glemt at låse døren.",
"En bold ryger ind gennem en åben dør.",
"En ven vælter en kop kakao ud over sofaen.",
"En hund løber direkte gennem en vandpyt og videre ind.",
"En familie forsøger at slå et telt op i blæsevejr.",
"En lillebror trykker på en knap, han ikke måtte røre.",
"En ven opdager, at nogen har læst en privat besked.",
"En familie opdager, at de står i den forkerte kø i en forlystelsespark.",
"En ballon sætter sig fast i loftlampen.",
"En ven har taget æren for noget, en anden har lavet.",
"En familie opdager, at komfuret stadig er tændt.",
"En søskende har ødelagt noget, der betyder meget for en anden.",
"En ven overdriver en historie foran alle.",
"En familie opdager, at der lugter brændt i køkkenet.",
"En lillebror nægter at dele slikposen.",
"En ven opdager, at der ikke er plads i bussen.",
"En bold rammer en bil på parkeringspladsen.",
"En familie opdager, at nogen har gemt fjernbetjeningen.",
"En ven har glemt sit kostume til en fest.",
"En lillebror har hældt alt for meget sæbe i badekarret.",
"En ven opdager, at en hemmelig plan er blevet afsløret.",
"En familie opdager, at fryseren er tøet op.",
"En mobil ringer højt midt i en vigtig samtale.",
"En ven opdager, at én ikke er blevet inviteret.",
"En familie står i snevejr med en bil, der sidder fast.",
"En bold triller ned ad en stejl bakke mod vejen.",
"En ven opdager, at nogen har ændret reglerne i spillet.",
"En lillebror gemmer sig med fjernbetjeningen.",
"En familie opdager, at nogen har taget den sidste sodavand i køleskabet.",
"En ven falder i en vandpyt foran de andre.",
"En familie opdager, at alarmen pludselig går i gang.",
"En søskende har spist noget, der var gemt til senere.",
"En ven har sendt et pinligt billede i en gruppechat.",
"En familie opdager, at de har glemt pas på ferien.",
"En bold lander midt i en picnic.",
"En ven står med en ødelagt gave i hænderne.",
"En lillebror nægter at tage jakke på i kulden.",
"En familie opdager, at nogen har gemt nøglerne.",
"En ven opdager, at nogen har set deres dagbog."
];

// We keep track of used scenarios in memory to avoid repetition within the same session if possible
let usedIndices: number[] = [];

export const generateScenario = async (): Promise<string> => {
  // Simulate a "thinking" delay for effect (3 seconds)
  // This makes the UI feel like it's processing, which builds anticipation
  await new Promise(resolve => setTimeout(resolve, 3000));

  if (usedIndices.length >= SCENARIOS.length) {
    // Reset if we've used all scenarios
    usedIndices = [];
  }

  let index;
  do {
    index = Math.floor(Math.random() * SCENARIOS.length);
  } while (usedIndices.includes(index));

  usedIndices.push(index);
  return SCENARIOS[index];
};